# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Petar Yanakiev
title: iOS App Developer 
email: petaryanakiev.py@gmail.com
phone: +359887097927
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  petaryanakiev-py
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: petaryanakiev-py
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Petar and I'm an iOS developer. Beyond shipping apps, I'm passionate about software engineering as a whole - from brainstorming ideas to delivering software that is actually used by someone.

  I love following Apple events, and <mark>WWDC</mark> is one of my favourites - every session feels like a peek at where the platform is headed next.

  My favourite problems are architectural ones, but I work hard to keep solutions as simple as they can be.

  In my free time, I co-organize iOS talks as part of Xcoders meetup in Sofia.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Days Since
        link: https://apps.apple.com/bg/app/days-since-quit-habit-tracker/id1445348921
        # link_text: Project Website
        additional_links:
          - title:  Days Dince
            url: https://apps.apple.com/bg/app/days-since-quit-habit-tracker/id1445348921
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Days Since is probably the best habit-quitting iOS app out there in the App Store.
        description: | # this will include new lines to allow paragraphs
          This app was started by a group of friends having an idea of motivating people to quit bad habits. That easily grabbed my interest, and when they suggested me to join their team as part-time developer, that was absolutely a no-brainer for me.
          I am developing features for the app in my free time. Working on it helps me understand the whole process of developing and shipping an app to production. I thought it was simple, but with Days Dince I changed my mind.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Devexperts
        link: https://devexperts.com
        # link_text: boringcompany.com
        sub_title: iOS Developer
        caption: March 2024 - Present
        description: | # this will include new lines to allow paragraphs
            - Developed and maintained a complex, active trading iOS application for the banking sector, including real-time data via <mark>WebSockets</mark>. 
            - Tackled difficult problems, including performance issues, memory leaks, and concurrency faults.
            - Implemented intuitive native designs in conformance with Apple's Human Interface Guidelines using <mark>SwiftUI</mark>.
            - Led an initiative for <mark>SPM</mark> modularization of the project and made it to production code.

      - layout: left
        title: Paysafe
        link: https://www.paysafe.com
        # link_text: boringcompany.com
        sub_title: iOS Developer
        caption: September 2020 - October 2023
        description: | # this will include new lines to allow paragraphs
            - Developed and maintained iOS applications for financing, sending money, and crypto trading.
            - Collaborated with cross-functional teams including designers and backend engineers to deliver high-quality apps.
            - Implemented user interface designs, application logic, and data persistence using <mark>Swift</mark> and <mark>UIKit</mark>.
            - Integrated RESTful APIs for data retrieval and synchronization with server-side systems.
            - Conducted testing, debugging, and performance optimizations to ensure app stability and responsiveness.
            - Collaborated in code reviews to maintain code quality and ensure adherence to best practices.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sofia University St. Kliment Ohridski
        caption: 2017 - 2021
        sub_title: BSc Software Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Sofia University, I learnt most of my key computer science and soft skills that I have taken through my career. I made contacts that continue to help me in my personal and career path of becoming a better person and engineer.

          I spent a semester as a teaching assistant of the *Object Oriented Programming* course during my 3rd year at the university. Arranged practice sessions with students, teaching them the basics of object oriented principles and designs in C++.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Swift and mobile apps some of my other interests and hobbies are:
      - Traveling ✈️
      - Football ⚽️
      - Running 🏃
      - Reading 📖
      - Drone Photography 📸

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
